### ISSUE TITLE
Running PCSX games with bios crash kodi

### ISSUE THREAD

**Issue by matejmosko** [kodi-game/game.libretro.pcsx-rearmed#13]
This behaviour started after libretroí compatiblity was upgraded to 1.0.38.107. Before, games worked quite fine. 

Starting any game results in black screen, kodi freezing not responding to any buttonclicks and eventually to rebooting. I have tried to delete .sav and .xml files - no change. This is a regression. It worked fine before. 

Important: Before the upgrade every first run of a game resulted in a black screen, but kodi didn't freeze. All consecutive runs of a game were successful. Therefore this is not the same as #9 

Kodi: Libreelec (Milhouse's build 715)
System: RPi3
[Kodi log](http://paste.kodi.tv/badejipipu)
[Crash log](http://paste.kodi.tv/hojoyudaga)

**Comment by garbear** [comment]
I think I fixed this a while ago, but can't find the commit now. IIRC the problem was that audio packets were arriving too early. @lrusak did you hang onto that commit?

**Comment by garbear** [comment]
https://github.com/xbmc/xbmc/pull/14194

**Comment by matejmosko** [comment]
Unfortunately, it didn't help. I upgraded to milhouse's 718 and the result is same.

Log: http://paste.kodi.tv/vimorayoze
Crash log: http://paste.kodi.tv/sikokekahi

**Comment by garbear** [comment]
Can you try https://github.com/xbmc/xbmc/pull/14203?

**Comment by GTechAlpha** [comment]
Also https://github.com/libretro/pcsx_rearmed/pull/178 .

**Comment by matejmosko** [comment]
Ok, so I will wait until cores are updates again sometime in future.

**Comment by matejmosko** [comment]
Bad news. It didn't help. All necesary PRs are finally in milhouse's libreelec build (pcsx is updated as well), but psx games still freeze and crash kodi.

Kodi log: http://paste.kodi.tv/atutaxuviy
Crash log: http://paste.kodi.tv/hadamusepi

@garbear, @GTechAlpha, any ideas?

**Comment by GTechAlpha** [comment]
The stack trace in your log is identical to what I experienced before https://github.com/libretro/pcsx_rearmed/pull/178 was applied. I think the fix didn't make it in to the build you're using, somehow.

**Comment by matejmosko** [comment]
I am not sure how it is possible. According to this commit https://github.com/LibreELEC/LibreELEC.tv/pull/2852/commits/88dc980f996cfdece79563caca70b36bf79eb767 pcsx in libreelec now includes all commits including yours. I have double checked, my pcsx addon is updated to this version.

**Comment by matejmosko** [comment]
Thanks @cdu13a, renaming bios folder so games run without bios makes them work on milhouse's libreelec. I haven't encountered any stuttering yet.

**Comment by matejmosko** [comment]
Just for future reference, ghizzu repprted similar issue on retroplaer forums https://forum.kodi.tv/showthread.php?tid=173361&pid=2759077#pid2759077

**Comment by garbear** [comment]
Ghizzu's error is fixed: https://github.com/xbmc/xbmc/pull/14313

**Comment by matejmosko** [comment]
Not yet confirmed on libreelec. Tommorov I will test new milhouse's build and report.

**Comment by cdu13a** [comment]
@matejmosko sorry I wasn't more specific. it was a build of libreelec I tested this on.

**Comment by matejmosko** [comment]
I have tested milhouses 817 now. For me it didn't help at all. The behaviour is still the same. Playing with bioses crashes kodi, playing without them suffer from stuttering. Have you done anything else except upgrading?

**Comment by matejmosko** [comment]
Ok, I probably managed to get it to work. I have downgraded back to milhouse's 816, uninstalled pcsx-rearmed addon (purged settings as well), then reinstalled pcsx, upgraded back to 817,  uploaded put bioses in proper folder and now it seemed to finally work. 

However, then I tried to reboot, to make sure that the current state of things preserves. And voila: here we are again. Same problems as above. Any ideas @garbear ?

**Comment by cdu13a** [comment]
@matejmosko I just did the same thing on milhouse #817 as I did on my own test build.

deleted the .sav files
uninstalled the game addons(removing settings)
updated libreelec
reinstalled game.libretro and game.libretro.pcsx-rearmed both from the libreelec addons repo
added bios files,
loaded several different games, played a bit. (all games bin/cue format)
played crash bandicoot for 30 min

This was on a pi2. So did not get full speed from the games. A bit of a lag and some audio issues. However other cores also don't hit full speed on the same device, and other parts of kodi are slow as well so that's probably not pcsx specific. (At least not while using a bios file)

**Comment by garbear** [comment]
A confounding factor could be both in-game saves and memory saves (savestates). In-game saves are placed in userdata, savestates next to the ROM. Maybe the presence of either of these is affecting the results?

**Comment by matejmosko** [comment]
Ok, I have tried to delete savestates as well as ingame saves now. No difference. Game with bios crashes kodi.

**Comment by garbear** [comment]
OK, next step we cut kodi out of the equation. Can this be reproduced on RetroArch?

**Comment by garbear** [comment]
I'll try to reproduce on desktop Ubuntu with Kodi

**Comment by cdu13a** [comment]
I didn't think of testing after a reboot, to see if it changed anything. After all why should a reboot change anything.

Possibly related is that pcsx-rearmed doesn't respect it's settings, on reset of the core. So it is possible to have the bios/boot logo in the savestate, when the core is not set to show it, which results in a crash on launch of the game.

**Comment by GTechAlpha** [comment]
Reverting https://github.com/xbmc/xbmc/commit/2bbd26fe51d36f0e0f55696d84a43a8910578288 fixes it for me.

**Comment by garbear** [comment]
Reverting the commit fixes the crash when running PCSX games with a bios? I can look into this, but there seems to be several problems listed in this issue.

**Comment by GTechAlpha** [comment]
> Reverting the commit fixes the crash when running PCSX games with a bios?

Yes.

**Comment by garbear** [comment]
OK. The bug is logged in https://github.com/garbear/xbmc/issues/80. I'm actually starting a new job soon so time might be a little too tight for me. But at least you identified the offending commit.

**Comment by KOPRajs** [comment]
Hi,
I've come here to fill in a bug report but it seems I'm late to the party. It looks like the PCSX-rearmed core needs to be initialized without BIOS for the first time. After first run without BIOS you can place the BIOS back and everything works until next Kodi restart. If there is a BIOS file present upon first run it crashes while trying to load it. It seems like there is an uninitialized variable related to BIOS loading.

Users see black screen because LibreELEC launches gdb in background to create a core dump and it takes a while.

**Comment by hansbogert** [comment]
> 
> 
> Hi,
> I've come here to fill in a bug report but it seems I'm late to the party. It looks like the PCSX-rearmed core needs to be initialized without BIOS for the first time. After first run without BIOS you can place the BIOS back and everything works until next Kodi restart. If there is a BIOS file present upon first run it crashes while trying to load it. It seems like there is an uninitialized variable related to BIOS loading.
> 
> Users see black screen because LibreELEC launches gdb in background to create a core dump and it takes a while.

You sure? In my case just seems to crash on the fact that there is savestate (not in-game)

**Comment by KOPRajs** [comment]
I'm still not 100% sure what's the root cause of the problem but it seems that moving Streams().Initialize() back to InitializeGameplay() solves it.

@garbear Please look at the patch. If it is safe I can create a PR.
https://github.com/KOPRajs/xbmc/commit/66df8118efdb6090d739fbf96f20d3b4fe78254f

Also I've discovered another code path where the current master crashes with PCSX-rearmed and BIOS:
1. Restart Kodi.
2. Run any PSX game without controllers connected.
3. Press back on the controllers info screen.
4. Select Exit in the game OSD.
In this case Kodi crashes on RetroPlayer deinitialization. The above patch seems to fix this as well.

P.S. Possibly the BIOS itself is not the cause, more likely the lack of BIOS triggers an error during initialization and that changes the code path and avoids the crash.

**Comment by KOPRajs** [comment]
@garbear Do you remember what was the reason to move the Streams().Initialize() from the InitializeGameplay() to OpenFile() in the PR #14146?

**Comment by garbear** [comment]
Kind of. The libretro API is underspecified as to when these functions should be called. See what information you gleam: https://github.com/kodi-game/game.libretro/blob/master/src/libretro/libretro.h

To see if your patch is correct, you need to map it to which libretro API calls happen when. At the end of the day it's all about libretro. Try to follow the existing code to libretro calls and see if the order violates libretro specification or conflicts with the order expected by the core.

**Comment by garbear** [comment]
I just re-read the PR and it seems I was very explicit in why the function was moved. Check the individual commit messages. If you still need help I don't have any development hardware but I can follow and explain the source code.

**Comment by KOPRajs** [comment]
I've read both the PR description and the individual commit messages. It seems that most of it applies to the split of the CGameClientInput::Initialize() to CGameClientInput::Start() and CGameClientInput::Deinitialize() to CGameClientInput::Stop() and to the changed order of related calls to solve the segfault caused by connecting the controllers too early. The above patch does not revert anything of that.

Then there is a statement saying: "This commit also corrects the order of init/deinit for other game add-on resources."
I believe it applies to the move of Streams().Initialize(), Streams().Deinitialize() and a few playstate variables. I can see why the Streams().Deinitialize() and the playstate variables were moved to the if statement but it is not clear why Streams().Initialize() was moved from InitializeGameplay() to OpenFile(). 

The above patch only reverts the Streams().Initialize(), the rest of the original commit is left intact.

**Comment by KOPRajs** [comment]
Since everything works for some time now I would consider closing this as solved.

Or are there any known drawbacks related to the revert?

**Comment by garbear** [comment]
Shall I close?

**Comment by KOPRajs** [comment]
We have moved Streams().Initialize() back to InitializeGameplay() before Leia release more than 2 years ago and I haven't heard about any related problems since then.

Maybe it is going to be revised when we finally get GL support (I really hope for this to happen as soon as possible).

**Comment by KOPRajs** [comment]
Well, it's been 5 years since we fixed this. Time to close this? ;-)
